"""Create tables zookeeper, enclosure and animal

Revision ID: 44188908e194
Revises: 7ca1c6f629a8
Create Date: 2023-09-23 09:27:57.169991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44188908e194'
down_revision = '7ca1c6f629a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('environment', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('open_to_visitors', sa.Boolean(), nullable=True))

    with op.batch_alter_table('enclosures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('environment', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('open_to_visitors', sa.Boolean(), nullable=True))

    with op.batch_alter_table('zookeepers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('birthday', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zookeepers', schema=None) as batch_op:
        batch_op.drop_column('birthday')
        batch_op.drop_column('name')

    with op.batch_alter_table('enclosures', schema=None) as batch_op:
        batch_op.drop_column('open_to_visitors')
        batch_op.drop_column('environment')

    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_column('open_to_visitors')
        batch_op.drop_column('environment')

    # ### end Alembic commands ###
